#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  bridge-utils
#  curl
#  libvirt-bin
#  openjdk-8-jdk
#  qemu-kvm
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/android"
homeDir="$baseDir/home"
installDir="$baseDir/install/studio"
tmpDir=$(mktemp -d /tmp/android-studio.XXXXXXXX)
pkgUrl=$(
	curl -sL 'https://developer.android.com/studio/index.html' |
	egrep -o 'https://dl\.google\.com/[^>]+/android-studio-ide-[^>]+-linux\.zip' |
	head -1
)

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

cat > ./bin/custom.vmoptions <<EOF
-Duser.home=$homeDir
EOF

mv "$tmpDir"/* "$installDir"

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'android-studio' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
export STUDIO_VM_OPTIONS="$installDir/bin/custom.vmoptions"
export ANDROID_HOME="$baseDir/install/sdk"
export PATH=\${PATH}:\$ANDROID_HOME/tools:\$ANDROID_HOME/platform-tools
"$installDir"/bin/studio.sh "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'android-studio' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Categories=Development;IDE;
Keywords=android;studio;ide;
StartupNotify=true
StartupWMClass=jetbrains-studio
Terminal=false
Exec=$binDir/android-studio %f
Icon=android-sdk
MimeType=application/x-extension-iml;
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

