#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  automake
#  build-essential
#  git
#  gnome-themes-standard
#  gtk2-engines-murrine
#  libgtk-3-dev
#  pkg-config
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
installDir='/usr/share/themes'
tmpDir=$(mktemp -d /tmp/arc-gtk-theme.XXXXXXXX)
gitUrl='https://github.com/horst3180/arc-theme.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Building...'
./autogen.sh --prefix=/usr

printAction 'Installing...'
sudo rm -rf "$installDir"/{Arc,Arc-Darker,Arc-Dark}

sudo make install

printAction 'Removing temp files...'
rm -rf "$tmpDir"

