#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  automake
#  build-essential
#  git
#  pkg-config
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
installDir='/usr/share/icons'
tmpDir=$(mktemp -d /tmp/arc-icon-theme.XXXXXXXX)
gitUrl='https://github.com/horst3180/arc-icon-theme.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Building...'
./autogen.sh --prefix=/usr

sed -i 's|^\(Inherits=\).*|\1Paper,elementary,elementary-git,Adwaita,gnome,hicolor|g' \
	./Arc/index.theme

printAction 'Installing...'
sudo rm -rf "$installDir"/Arc

sudo doMake install
sudo gtk-update-icon-cache -f "$installDir"/Arc

printAction 'Removing temp files...'
rm -rf "$tmpDir"

