#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Downloads:
#  stable: https://atom.io/download/deb
#  beta:   https://atom.io/download/deb?channel=beta
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/atom"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/atom.XXXXXXXX)
pkgUrl='https://atom.io/download/deb'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

mv "$tmpDir"/* "$installDir"

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'atom' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/usr/bin/atom "\$@"
EOF
)"
createWrapper "$installDir" "$binDir" 'apm' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/usr/bin/apm "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'atom' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Atom
Categories=Development;IDE;TextEditor;Utility;
Keywords=atom;code;
StartupNotify=true
Terminal=false
Exec=$binDir/atom %F
Icon=atom
MimeType=text/plain;
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

