#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  build-essential
#  cmake
#  git
#  libqt5opengl5-dev
#  libsdl2-dev
#  qtbase5-dev
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/citra"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/citra.XXXXXXXX)
gitUrl='https://github.com/citra-emu/citra.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Building...'
doCmake \
	-D CMAKE_INSTALL_PREFIX="$installDir" \
	-D CMAKE_CXX_FLAGS="-O2 -std=gnu++14 -march=native" \
	-D CMAKE_BUILD_TYPE=Release
doMake

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

mv -t "$installDir" \
	"$tmpDir"/build/src/{citra/citra,citra_qt/citra-qt} \
	"$tmpDir"/dist/citra.svg

if [ ! -f "$homeDir"/.config/citra-emu/qt-config.ini ]; then
	mkdir -p "$homeDir"/.config/citra-emu
	cat > "$homeDir"/.config/citra-emu/qt-config.ini <<-'EOF'
	[System]
	region_value=2
	EOF
fi

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'citra' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/citra "\$@"
EOF
)"
createWrapper "$installDir" "$binDir" 'citra-qt' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/citra-qt "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'citra' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Citra
Categories=Game;Emulator;
Keywords=nintendo;3ds;emulator;
StartupNotify=true
Terminal=true
Exec=$binDir/citra-qt %f
#Icon=citra
Icon=$installDir/citra.svg
MimeType=application/x-ctr-3dsx;application/x-ctr-cci;application/x-ctr-cia;application/x-ctr-cxi;
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

