#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  automake
#  build-essential
#  dos2unix
#  gettext
#  intltool
#  libagg-dev
#  libasound2-dev
#  libgl1-mesa-dev
#  libglade2-dev
#  libglib2.0-dev
#  libglu1-mesa-dev
#  libgtk2.0-dev
#  libgtkglext1-dev
#  liblua5.1-0-dev
#  libopenal-dev
#  libpcap-dev
#  libsdl1.2-dev
#  libsoundtouch-dev
#  libzzip-dev
#  zlib1g-dev
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/desmume"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/desmume.XXXXXXXX)
gitUrl='https://github.com/TASVideos/desmume.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Building...'
cd ./desmume

# Change firmware settings
dos2unix ./src/firmware.cpp
patch ./src/firmware.cpp <<'EOF'
--- src/firmware.cpp
+++ src/firmware.cpp
@@ -906 +906 @@
-	const char *default_nickname = "DeSmuME";
+	const char *default_nickname = "Zant";
@@ -907 +907 @@
-	const char *default_message = "DeSmuME makes you happy!";
+	const char *default_message = "Ceci n'est pas un pepe";
@@ -914 +914 @@
-	fw_config->fav_colour = 7;
+	fw_config->fav_colour = 0;
@@ -916 +916 @@
-	fw_config->birth_day = 23;
+	fw_config->birth_day = 9;
@@ -917 +917 @@
-	fw_config->birth_month = 6;
+	fw_config->birth_month = 3;
@@ -932 +932 @@
-	fw_config->language = 1;
+	fw_config->language = 5;
EOF

cd ./src/frontend/posix
doConfigureAndMake \
	--prefix="$installDir" \
	--enable-debug \
	--enable-glade \
	--enable-glx \
	--enable-hud \
	--enable-openal \
	--enable-osmesa \
	--enable-wifi

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir"/.local/share "$installDir"

doMake install

if [ ! -f "$homeDir"/.config/desmume/config.cfg ]; then
	mkdir -p "$homeDir"/.config/desmume
	cat > "$homeDir"/.config/desmume/config.cfg <<-'EOF'
	[View]
	ScreenLayout=1
	ShowToolbar=false
	ShowStatusbar=false
	Filter=4
	SecondaryFilter=3

	[Audio]
	Synchronization=3
	Interpolation=1

	[Config]
	FpsLimiter=true
	AudoFrameskip=true
	Frameskip=2
	EOF
fi

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'desmume' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/bin/desmume \
	--jit-enable \
	--jit-size 15 \
	--preload-rom \
	--lang 5 \
	"\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'desmume' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=DeSmuME
Categories=Game;Emulator;
Keywords=nintendo;ds;emulator;
StartupNotify=true
Terminal=true
Exec=$binDir/desmume %f
#Icon=desmume
Icon=$installDir/share/pixmaps/DeSmuME.xpm
MimeType=application/x-nintendo-ds-rom;
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

