#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  curl
#  openjdk-8-jdk
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/eclipse-jee"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/eclipse-jee.XXXXXXXX)
pkgBaseUrl='https://www.mirrorservice.org/sites/download.eclipse.org/eclipseMirror/technology/epp/downloads/release'
pkgVersion=$(curl -sL "$pkgBaseUrl/release.xml" | sed -nE 's/<present>(.+)<\/present>/\1/g;/^</!p')
pkgUrl="$pkgBaseUrl/$pkgVersion"/$(
	curl -sL "$pkgBaseUrl/$pkgVersion" | \
	egrep -o 'eclipse-jee-[^>]+-linux-gtk-x86_64\.tar\.gz' | \
	head -1
)

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir" ./configuration/.settings

cat > ./configuration/.settings/org.eclipse.ui.ide.prefs <<-EOF
RECENT_WORKSPACES=$HOME/Projects/Eclipse
RECENT_WORKSPACES_PROTOCOL=3
SHOW_WORKSPACE_SELECTION_DIALOG=true
eclipse.preferences.version=1
EOF

cat >> ./eclipse.ini <<-EOF
-Duser.home=$homeDir
EOF

# Force GTK2 due multiple issues with GTK3
sed -i '/--launcher.appendVmargs/i\--launcher.GTK_version\n2' ./eclipse.ini

mv "$tmpDir"/* "$installDir"

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'eclipse-jee' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/eclipse "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'eclipse-jee' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Eclipse
Categories=Development;IDE;Java;
Keywords=eclipse;ide;
StartupNotify=true
Terminal=false
Exec=$binDir/eclipse-jee %f
StartupWMClass=Eclipse
Icon=eclipse
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

