#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  git
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
installDir='/usr/share/icons/elementary-git'
tmpDir=$(mktemp -d /tmp/elementary-icon-theme.XXXXXXXX)
gitUrl='https://github.com/elementary/icons.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Installing...'
sudo rm -rf "$installDir"
sudo mkdir -p "$installDir"

sed -i 's|^\(Name=\).*|\1elementary-git|g' \
	./index.theme

sed -i 's|^\(Name=\).*|\1elementary-git|g;s|^\(Inherits=\).*|\1elementary-git|g;' \
	./cursor.theme

sudo mv "$tmpDir"/* "$installDir"
sudo gtk-update-icon-cache -f "$installDir"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

