#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/firefox-esr"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/firefox-esr.XXXXXXXX)
pkgUrl='https://download.mozilla.org/?lang=en-US&os=linux64&product=firefox-esr-latest'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

mv "$tmpDir"/* "$installDir"

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'firefox-esr' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/firefox "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'firefox-esr' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Mozilla Firefox ESR
Categories=Network;WebBrowser;
Keywords=Internet;WWW;Browser;Web;Explorer;
Terminal=false
StartupNotify=true
Exec=$binDir/firefox-esr %u
Icon=firefox-esr
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
Actions=NewTab;NewWindow;NewPrivateWindow;

[Desktop Action NewTab]
Name=Open new tab
Exec=$binDir/firefox-esr -new-tab about:newtab

[Desktop Action NewWindow]
Name=Open new window
Exec=$binDir/firefox-esr -new-window

[Desktop Action NewPrivateWindow]
Name=Open new private window
Exec=$binDir/firefox-esr -private-window
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

