#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  curl
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
installDir='/usr/share/fonts/opentype/Hack'
tmpDir=$(mktemp -d /tmp/hack-font.XXXXXXXX)
pkgUrl='https://github.com'$(
	curl -sL 'https://github.com/chrissimpkins/Hack/releases/latest' | \
	egrep -o '/chrissimpkins/Hack/releases/download/[^>]+/Hack-.+-otf\.tar\.gz' | \
	head -1
)

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
sudo rm -rf "$installDir"
sudo mkdir -p "$installDir"

sudo mv -v "$tmpDir"/*.otf "$installDir"
fc-cache -fv "$installDir"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

