#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  automake
#  build-essential
#  cmake
#  git
#  libavcodec-dev
#  libavformat-dev
#  libavresample-dev
#  libavutil-dev
#  libedit-dev
#  libepoxy-dev
#  libmagickwand-dev
#  libminizip-dev
#  libpng-dev
#  libqt5opengl5-dev
#  libsdl2-dev
#  libswscale-dev
#  libzip-dev
#  qtbase5-dev
#  qtmultimedia5-dev
#  qttools5-dev-tools
#  zlib1g-dev
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/mgba"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/mgba.XXXXXXXX)
gitUrl='https://github.com/mgba-emu/mgba.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Building...'
doCmake \
	-D CMAKE_INSTALL_PREFIX="$installDir" \
	-D BUILD_STATIC=ON \
	-D BUILD_SHARED=ON \
	-D CMAKE_BUILD_TYPE=Release
doMake

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

doMake install

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'mgba' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
export LD_LIBRARY_PATH="$installDir/lib"
"$installDir"/bin/mgba "\$@"
EOF
)"
createWrapper "$installDir" "$binDir" 'mgba-qt' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
export LD_LIBRARY_PATH="$installDir/lib"
"$installDir"/bin/mgba-qt "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'mgba' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=mGBA
Categories=Game;Emulator;
Keywords=nintendo;gba,gbc;emulator;
StartupNotify=true
Terminal=false
Exec=$binDir/mgba-qt %f
Icon=mgba
MimeType=application/x-gameboy-advance-rom;application/x-agb-rom;application/x-gba-rom;
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

