#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  git
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
installDir='/usr/share/themes/Paper'
tmpDir=$(mktemp -d /tmp/paper-gtk-theme.XXXXXXXX)
gitUrl='https://github.com/snwh/paper-gtk-theme.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Installing...'
sudo rm -rf "$installDir"
sudo mkdir -p "$installDir"

sudo mv "$tmpDir"/Paper/* "$installDir"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

