#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  curl
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/popcorntime"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/popcorntime.XXXXXXXX)
pkgUrl=$(
	curl -sL 'https://popcorntime.sh/en' | \
	egrep -o 'https://[^>]+-Linux-64\.tar\.xz' | \
	head -1
)

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

mv "$tmpDir"/* "$installDir"

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'popcorntime' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/Popcorn-Time "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'popcorntime' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Popcorn Time
Categories=AudioVideo;Video;Network;Player;P2P;
Keywords=popcorn;tv;show;movie;
StartupNotify=true
StartupWMClass=crx_hecfofbbdfadifpemejbbdcjmfmboohj
Terminal=false
Exec=$binDir/popcorntime %u
Icon=popcorntime
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

