#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Downloads:
#  linux64-stable: http://go.microsoft.com/fwlink/?LinkID=620884
#  linux64-insider: https://go.microsoft.com/fwlink/?LinkId=723968
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/vscode"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/vscode.XXXXXXXX)
pkgUrl='http://go.microsoft.com/fwlink/?LinkID=620884'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

mv "$tmpDir"/* "$installDir"

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'vscode' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/code "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'vscode' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Visual Studio Code
Categories=Development;IDE;TextEditor;Utility;
Keywords=code;vscode;
StartupNotify=true
Terminal=false
Exec=$binDir/vscode %U
Icon=visual-studio-code
MimeType=text/plain;

[Desktop Action new-window]
Name=New Window
Exec=$binDir/vscode --new-window %U
Icon=visual-studio-code
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

