#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  curl
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/webtorrent"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/webtorrent.XXXXXXXX)
pkgUrl='https://github.com'$(
	curl -sL 'https://github.com/feross/webtorrent-desktop/releases/latest' | \
	egrep -o '/feross/webtorrent-desktop/releases/download/[^>]+/WebTorrent-[^>]+-linux\.zip' | \
	head -1
)

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Downloading package...'
downloadExtractAndCd "$pkgUrl" "$tmpDir"

printAction 'Installing...'
rm -rf "$installDir" "$baseDir"
mkdir -p "$binDir" "$homeDir"/Downloads "$installDir"

mv "$tmpDir"/* "$installDir"

if [ ! -f "$homeDir"/.config/WebTorrent/config.json ]; then
	mkdir -p "$homeDir"/.config/WebTorrent
	cat > "$homeDir"/.config/WebTorrent/config.json <<-EOF
	{
	  "prefs": {
	    "downloadPath": "$homeDir/Downloads"
	  },
	  "torrents": [],
	  "version": "999.999.999"
	}
	EOF
fi

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'webtorrent' "$(cat <<-EOF
#!/usr/bin/env bash
export HOME="$homeDir"
export XDG_CONFIG_HOME="$homeDir/.config"
export XDG_CACHE_HOME="$homeDir/.cache"
export XDG_DATA_HOME="$homeDir/.local/share"
"$installDir"/WebTorrent "\$@"
EOF
)"

printAction 'Creating launchers...'
createLauncher "$installDir" 'webtorrent' "$(cat <<-EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=WebTorrent
Categories=AudioVideo;Video;Network;Player;P2P;
Keywords=torrent;stream;
StartupNotify=true
Terminal=false
Exec=$binDir/webtorrent %U
#Icon=webtorrent
Icon=$installDir/resources/app.asar.unpacked/static/WebTorrent.png
MimeType=application/x-bittorrent;x-scheme-handler/magnet;x-scheme-handler/stream-magnet;
Actions=CreateNewTorrent;OpenTorrentFile;OpenTorrentAddress;

[Desktop Action CreateNewTorrent]
Name=Create new torrent...
Exec=$binDir/webtorrent -n

[Desktop Action OpenTorrentFile]
Name=Open torrent file...
Exec=$binDir/webtorrent -o

[Desktop Action OpenTorrentAddress]
Name=Open torrent address...
Exec=$binDir/webtorrent -u
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

