#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  docker.io | docker-engine
#  git
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
binDir="$HOME/.opt/bin"
baseDir="$HOME/.opt/zeronet"
homeDir="$baseDir/home"
installDir="$baseDir/install"
tmpDir=$(mktemp -d /tmp/zeronet.XXXXXXXX)
gitUrl='https://github.com/HelloZeroNet/ZeroNet.git'

# Load helpers
source "$scriptDir"/_helpers_

# Process
printAction 'Cloning remote repository...'
doGitCloneAndCd "$gitUrl" "$tmpDir"

printAction 'Building Docker image...'
cat > ./Dockerfile <<-EOF
FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

# Install packages
RUN \
	apt-get update -y; \
	apt-get install -y git python python-gevent python-msgpack tor; \
	apt-get clean; \
	rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

# Create ZeroNet user
RUN addgroup \
	--gid $(id -g "$(whoami)") \
	zeronet
RUN adduser \
	--home /home/zeronet \
	--uid $(id -u "$(whoami)") \
	--ingroup zeronet \
	--disabled-password \
	--gecos '' \
	zeronet
WORKDIR /home/zeronet

# Add ZeroNet source
ADD . /home/zeronet
VOLUME /home/zeronet/data

# Configure tor
RUN \
	echo "RunAsDaemon 1" >> .torrc; \
	echo "ControlPort 9051" >> .torrc; \
	echo "CookieAuthentication 1" >> .torrc

# Set ZeroNet user permissions
RUN chown -R zeronet:zeronet /home/zeronet

# Set upstart command
CMD \
	tor -f .torrc; \
	python ./zeronet.py \
		--fileserver_ip 0.0.0.0 \
		--fileserver_port 15441 \
		--ui_ip 0.0.0.0 \
		--ui_port 43110 \
		--tor enable

# Expose ports
EXPOSE 15441
EXPOSE 43110
EOF

docker build --rm --tag zeronet .

printAction 'Installing...'
rm -rf "$installDir"
mkdir -p "$binDir" "$homeDir" "$installDir"

printAction 'Creating wrappers...'
createWrapper "$installDir" "$binDir" 'zeronet' "$(cat <<-EOF
#!/usr/bin/env bash
docker run \
	--name zeronet \
	--publish 127.0.0.1:15441:15441 \
	--publish 127.0.0.1:43110:43110 \
	--volume "$homeDir":/home/zeronet/data \
	--user zeronet \
	--interactive \
	--tty \
	--rm \
	zeronet
EOF
)"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

