#!/bin/sh

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#

curl -s 'https://raw.githubusercontent.com/zant95/hblock/master/resources/stats.sh' | \
	tac | tac | sh -s - "$@"

