#!/bin/sh

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#

curl -sL 'https://github.com/zant95/hBlock/raw/master/android/make_flashable_zip_from_remote.sh' | sh
