#!/usr/bin/env bash

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  ffmpeg
#  mat
#  youtube-dl
#

# Exit on errors
set -euo pipefail

# Globals
scriptDir=$(dirname "$(readlink -f "$0")")
tmpDir=$(mktemp -d /tmp/music-dl.XXXXXXXX)
outDir="$HOME/Downloads"
ffmpegLoc=$(
	[ -f "$HOME/.opt/bin/ffmpeg" ] \
		&& echo "$HOME/.opt/bin/ffmpeg" || echo $(which ffmpeg)
)

# Load helpers
if [ -f "$scriptDir"/recipes/_helpers.sh ]; then
	source "$scriptDir"/recipes/_helpers.sh
else
	source <(curl -sL 'https://raw.githubusercontent.com/zant95/misc/master/scripts/recipes/_helpers.sh')
fi

# Process
mkdir -p "$tmpDir"/{before,after}
cd "$tmpDir"

infoMsg 'Downloading...'
youtube-dl "$@" \
	--ffmpeg-location "$ffmpegLoc" \
	--default-search 'ytsearch' \
	--format 'bestaudio' \
	--output "$tmpDir/before/%(title)s"

infoMsg 'Encoding to VBR MP3...'
for file in "$tmpDir/before"/*; do
	"$ffmpegLoc" \
		-hide_banner \
		-i "$file" \
		-codec:a libmp3lame \
		-qscale:a 2 \
		"$tmpDir/after/${file##*/}.mp3"
done

if type mat > /dev/null; then
	infoMsg 'Cleaning metadata...'
	mat "$tmpDir"/after/*.mp3
fi

infoMsg 'Moving to output folder...'
mkdir -p "$outDir"
mv -f "$tmpDir"/after/*.mp3 "$outDir"

infoMsg 'Removing temp files...'
rm -rf "$tmpDir"

