#!/bin/bash

# Author:
#  Héctor Molinero Fernández <hector@molinero.xyz>.
#
# Dependencies:
#  ffmpeg
#  mat
#  youtube-dl
#

# Exit on errors
set -eu -o pipefail

# Print message methods
printmsg() {
	echo -e "\e[1;33m + \e[1;32m$1 \e[0m"
}

# Globals
TMP_DIR="/tmp/music-dl"
OUT_DIR="$HOME/Downloads/Music-DL"
FFMPEG_LOC=$(
	[ -f "$HOME/.opt/bin/ffmpeg" ] \
		&& echo "$HOME/.opt/bin/ffmpeg" || echo $(which ffmpeg)
)

# Process
printmsg "Preparing workspace..."
rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"/{before,after}
cd "$TMP_DIR"

printmsg "Downloading..."
youtube-dl "$@" \
	--ffmpeg-location "$FFMPEG_LOC" \
	--default-search "ytsearch" \
	--format "bestaudio" \
	--output "$TMP_DIR/before/%(title)s"

printmsg "Encoding to VBR MP3..."
for FILE in "$TMP_DIR/before"/*; do
	"$FFMPEG_LOC" \
		-hide_banner \
		-i "$FILE" \
		-codec:a libmp3lame \
		-qscale:a 2 \
		"$TMP_DIR/after/${FILE##*/}.mp3"
done

if type mat > /dev/null; then
	printmsg "Cleaning metadata..."
	mat "$TMP_DIR"/after/*.mp3
fi

printmsg "Moving to output folder..."
mkdir -p "$OUT_DIR"
mv -f "$TMP_DIR"/after/*.mp3 "$OUT_DIR"

printmsg "Removing temp files..."
rm -rf "$TMP_DIR"

