#!/bin/sh

# Author:     Héctor Molinero Fernández <hector@molinero.xyz>
# Repository: https://github.com/zant95/misc
# License:    MIT, https://opensource.org/licenses/MIT
#
# Dependencies:
#  ffmpeg
#  mat
#  youtube-dl
#

# Exit on errors
set -eu

# Globals
tmpDir=$(mktemp -d /tmp/music-dl.XXXXXXXX)
outDir="$HOME/Downloads"

if [ -f "$HOME/.opt/bin/ffmpeg" ]; then
	ffmpegLoc="$HOME/.opt/bin/ffmpeg"
else
	ffmpegLoc=$(which ffmpeg)
fi

# Methods
printAction() {
	printf -- '\033[1;33m + \033[1;32m%s \033[0m\n' "$@"
}

# Process
mkdir -p "$tmpDir"/before "$tmpDir"/after
cd "$tmpDir"

printAction 'Downloading...'
youtube-dl "$@" \
	--ffmpeg-location "$ffmpegLoc" \
	--default-search 'ytsearch' \
	--format 'bestaudio' \
	--output "$tmpDir/before/%(title)s"

printAction 'Encoding to VBR MP3...'
for file in "$tmpDir/before"/*; do
	"$ffmpegLoc" \
		-hide_banner \
		-i "$file" \
		-codec:a libmp3lame \
		-qscale:a 2 \
		"$tmpDir/after/${file##*/}.mp3"
done

if type mat >/dev/null; then
	printAction 'Cleaning metadata...'
	mat "$tmpDir"/after/*.mp3
fi

printAction 'Moving to output folder...'
mkdir -p "$outDir"
mv -f "$tmpDir"/after/*.mp3 "$outDir"

printAction 'Removing temp files...'
rm -rf "$tmpDir"

